version: '3.9'

services:
  backend:
    container_name: video-generator-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /home/marotta/Movies:/app/output
    restart: unless-stopped
